# Generated by Django 4.0 on 2021-12-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'ya existe esta categoria'}, max_length=50, unique=True, verbose_name='Digite nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe esta marca en el sistema'}, max_length=50, unique=True, verbose_name='Digite nombre de la Marca')),
            ],
        ),
    ]
